///an instruction that sizes one byte: no argument only instruction (1b)
typealias OneByteInstruction    = ()              -> Void
///an instruction that sizes two bytes: instruction (1b) + one argument (1b)
typealias TwoBytesInstruction   = (Byte)          -> Void
///an instruction that'sizes three bytes: instruction (1b) + first argument (1b) + second argument (1b)
typealias ThreeBytesInstruction = (EnhancedShort) -> Void
//variable length instruction: a wrapper for One Two or Three bytes instruction (sadly swift doesn't support optional arg in closure)
typealias VariableLengthInstruction = (_ byte:Byte?,_ short:EnhancedShort?) -> Void

///shortcut to forward(one,nil,nil) as optional parameter must be filled
func forward(_ one:OneByteInstruction? = nil) -> VariableLengthInstruction? {
    return forward(one, nil, nil)
}

///shortcut to forward(one,nil,nil) as optional parameter must be filled
func forward(_ two:TwoBytesInstruction? = nil) -> VariableLengthInstruction? {
    return forward(nil, two, nil)
}

///shortcut to forward(nil,nil,three) as optional parameter must be filled
func forward(_ three:ThreeBytesInstruction? = nil) -> VariableLengthInstruction? {
    return forward(nil, nil, three)
}

///a function to convert any instruction to a more generic variable length wrapper
private func forward(_ one:OneByteInstruction? = nil,
             _ two:TwoBytesInstruction? = nil,
             _ three:ThreeBytesInstruction? = nil) -> VariableLengthInstruction? {
    if(one != nil) {
        return { _,_ in one!() }
    }
    else if(two != nil) {
        return { byte,short in two!(byte!) }
    }
    else if(three != nil) {
        return { byte,short in three!(short!) }
    }
    return nil
}

class InstructionDecoder {
    public static let sharedInstance = InstructionDecoder()
    
    private var instructionSet:[UInt8:Instruction] = [:]
    private var extendedInstructionSet:[UInt8:Instruction] = [:]
    
    public func setup(gbInstructions:GameBoyInstructionSet) {
        //standard instructions
        let instructions:[Instruction] = self.buildStandardInstructionSet(instructions: gbInstructions)
        self.instructionSet = Dictionary(uniqueKeysWithValues: instructions.map{($0.opCode,$0)})
        
        //0xCB instructions
        let extendedInstructions:[Instruction] = buildExtendedInstructionSet(instructions: gbInstructions)
        self.extendedInstructionSet = Dictionary(uniqueKeysWithValues: extendedInstructions.map{($0.opCode,$0)})
    }
    
    ///decode an opcode and return corresponding instruction or nil if not found/supported
    func decode(opCode:UInt8, isExtended:Bool = false) -> Instruction? {
        let instrSet = isExtended ? self.extendedInstructionSet : self.instructionSet
        if let instr = instrSet[opCode] {
            return instr
        }
        return nil
    }
    
    /// build standard instruction array from a StandardInstructionSet implementation
    private func buildStandardInstructionSet(instructions:StandardInstructionSet) -> [Instruction] {
        return [
            Instruction(opCode: 0x00, length: 1, name: "nop", duration:4, implementation: forward(instructions.nop)!),
            Instruction(opCode: 0x01, length: 3, name: "LD BC, 0x%04X", duration:12, implementation: forward(instructions.ld_bc_nn)!),
            Instruction(opCode: 0x02, length: 1, name: "LD (BC), A", duration:8, implementation: forward(instructions.ld_bcp_a)!),
            Instruction(opCode: 0x03, length: 1, name: "INC BC", duration:4, implementation: forward(instructions.inc_bc)!),
            Instruction(opCode: 0x04, length: 1, name: "INC B", duration:4, implementation: forward(instructions.inc_b)!),
            Instruction(opCode: 0x05, length: 1, name: "DEC B", duration:4, implementation: forward(instructions.dec_b)!),
            Instruction(opCode: 0x06, length: 2, name: "LD B, 0x%02X", duration:8, implementation: forward(instructions.ld_b_n)!),
            Instruction(opCode: 0x07, length: 1, name: "RLCA", duration:4, implementation: forward(instructions.rlca)!),
            Instruction(opCode: 0x08, length: 3, name: "LD (0x%04X), SP", duration:20, implementation: forward(instructions.ld_nnp_sp)!),
            Instruction(opCode: 0x09, length: 1, name: "ADD HL, BC", duration:8, implementation: forward(instructions.add_hl_bc)!),
            Instruction(opCode: 0x0A, length: 1, name: "LD A, (BC)", duration:8, implementation: forward(instructions.ld_a_bcp)!),
            Instruction(opCode: 0x0B, length: 1, name: "DEC BC", duration:8, implementation: forward(instructions.dec_bc)!),
            Instruction(opCode: 0x0C, length: 1, name: "INC C", duration:4, implementation: forward(instructions.inc_c)!),
            Instruction(opCode: 0x0D, length: 1, name: "DEC C", duration:4, implementation: forward(instructions.dec_c)!),
            Instruction(opCode: 0x0E, length: 2, name: "LD C, 0x%02X", duration:8, implementation: forward(instructions.ld_c_n)!),
            Instruction(opCode: 0x0F, length: 1, name: "RRCA", duration:4, implementation: forward(instructions.rrca)!),
            // Instruction(opCode: 0x10, length: 1, name: "STOP", duration:4, implementation: forward(instructions.stop)!),
            Instruction(opCode: 0x11, length: 3, name: "LD DE, 0x%04X", duration:12, implementation: forward(instructions.ld_de_nn)!),
            Instruction(opCode: 0x12, length: 1, name: "LD (DE), A", duration:8, implementation: forward(instructions.ld_dep_a)!),
            Instruction(opCode: 0x13, length: 1, name: "INC DE", duration:4, implementation: forward(instructions.inc_de)!),
            Instruction(opCode: 0x14, length: 1, name: "IND D", duration:4, implementation: forward(instructions.inc_d)!),
            Instruction(opCode: 0x15, length: 1, name: "DEC D", duration:4, implementation: forward(instructions.dec_d)!),
            Instruction(opCode: 0x16, length: 2, name: "LD D, 0x%02X", duration:8, implementation: forward(instructions.ld_d_n)!),
            Instruction(opCode: 0x17, length: 1, name: "RLA", duration:4, implementation: forward(instructions.rla)!),
            Instruction(opCode: 0x18, length: 2, name: "JR 0x%02X", duration:12, implementation: forward(instructions.jr_n)!),
            Instruction(opCode: 0x19, length: 1, name: "ADD HL, DE", duration:8, implementation: forward(instructions.add_hl_de)!),
            Instruction(opCode: 0x1A, length: 1, name: "LD A, (DE)", duration:8, implementation: forward(instructions.ld_a_dep)!),
            Instruction(opCode: 0x1B, length: 1, name: "DEC DE", duration:8, implementation: forward(instructions.dec_de)!),
            Instruction(opCode: 0x1C, length: 1, name: "INC E", duration:4, implementation: forward(instructions.inc_e)!),
            Instruction(opCode: 0x1D, length: 1, name: "DEC E", duration:4, implementation: forward(instructions.dec_e)!),
            Instruction(opCode: 0x1E, length: 2, name: "LD E, 0x%02X", duration:8, implementation: forward(instructions.ld_e_n)!),
            Instruction(opCode: 0x1F, length: 1, name: "RRA", duration:4, implementation: forward(instructions.rra)!),
            Instruction(opCode: 0x20, length: 2, name: "JR NZ, 0x%02X", duration:12, implementation: forward(instructions.jr_nz_n)!),
            Instruction(opCode: 0x21, length: 3, name: "LD HL, 0x%04X", duration:12, implementation: forward(instructions.ld_hl_nn)!),
            Instruction(opCode: 0x22, length: 1, name: "LD (HL+), A", duration:8, implementation: forward(instructions.ld_hlip_a)!),
            Instruction(opCode: 0x23, length: 1, name: "INC HL", duration:8, implementation: forward(instructions.inc_hl)!),
            Instruction(opCode: 0x24, length: 1, name: "INC H", duration:4, implementation: forward(instructions.inc_h)!),
            Instruction(opCode: 0x25, length: 1, name: "DEC H", duration:4, implementation: forward(instructions.dec_h)!),
            Instruction(opCode: 0x26, length: 2, name: "LD H, 0x%02X", duration:8, implementation: forward(instructions.ld_h_n)!),
            // Instruction(opCode: 0x27, length: 1, name: "DAA", duration:4, implementation: forward(instructions.daa)!),
            Instruction(opCode: 0x28, length: 2, name: "JR Z, 0x%02X", duration:12, implementation: forward(instructions.jr_z_n)!),
            Instruction(opCode: 0x29, length: 1, name: "ADD HL, HL", duration:8, implementation: forward(instructions.add_hl_hl)!),
            Instruction(opCode: 0x2A, length: 1, name: "LD A, (HL+)", duration:8, implementation: forward(instructions.ld_a_hlip)!),
            Instruction(opCode: 0x2B, length: 1, name: "DEC HL", duration:8, implementation: forward(instructions.dec_hl)!),
            Instruction(opCode: 0x2C, length: 1, name: "INC L", duration:4, implementation: forward(instructions.inc_l)!),
            Instruction(opCode: 0x2D, length: 1, name: "DEC L", duration:4, implementation: forward(instructions.dec_l)!),
            Instruction(opCode: 0x2E, length: 2, name: "LD L, 0x%02X", duration:8, implementation: forward(instructions.ld_l_n)!),
            Instruction(opCode: 0x2F, length: 1, name: "CPL", duration:4, implementation: forward(instructions.cpl)!),
            Instruction(opCode: 0x30, length: 2, name: "JR NC, 0x%02X", duration:12, implementation: forward(instructions.jr_nc_n)!),
            Instruction(opCode: 0x31, length: 3, name: "LD SP, 0x%04X", duration:12, implementation: forward(instructions.ld_sp_nn)!),
            Instruction(opCode: 0x32, length: 1, name: "LD (HL-), A", duration:8, implementation: forward(instructions.ld_hlpd_a)!),
            Instruction(opCode: 0x33, length: 1, name: "INC SP", duration:8, implementation: forward(instructions.inc_sp)!),
            Instruction(opCode: 0x34, length: 1, name: "INC (HL)", duration:12, implementation: forward(instructions.inc_hlp)!),
            Instruction(opCode: 0x35, length: 1, name: "DEC (HL)", duration:12, implementation: forward(instructions.dec_hlp)!),
            Instruction(opCode: 0x36, length: 2, name: "LD (HL), 0x%02X", duration:12, implementation: forward(instructions.ld_hlp_n)!),
            Instruction(opCode: 0x37, length: 1, name: "SCF", duration:4, implementation: forward(instructions.scf)!),
            Instruction(opCode: 0x38, length: 2, name: "JR C, 0x%02X", duration:8, implementation: forward(instructions.jr_c_n)!),
            Instruction(opCode: 0x39, length: 1, name: "ADD HL, SP", duration:4, implementation: forward(instructions.add_hl_sp)!),
            Instruction(opCode: 0x3A, length: 1, name: "LD A, (HL-)", duration:8, implementation: forward(instructions.ld_a_hlpd)!),
            Instruction(opCode: 0x3B, length: 1, name: "DEC SP", duration:8, implementation: forward(instructions.dec_sp)!),
            Instruction(opCode: 0x3C, length: 1, name: "INC A", duration:4, implementation: forward(instructions.inc_a)!),
            Instruction(opCode: 0x3D, length: 1, name: "DEC A", duration:4, implementation: forward(instructions.dec_a)!),
            Instruction(opCode: 0x3E, length: 2, name: "LD A, 0x%02X", duration:8, implementation: forward(instructions.ld_a_n)!),
            Instruction(opCode: 0x3F, length: 1, name: "CCF", duration:4, implementation: forward(instructions.ccf)!),
            Instruction(opCode: 0x40, length: 1, name: "LD B, B", duration:4, implementation: forward(instructions.ld_b_b)!),
            Instruction(opCode: 0x41, length: 1, name: "LD B, C", duration:4, implementation: forward(instructions.ld_b_c)!),
            Instruction(opCode: 0x42, length: 1, name: "LD B, D", duration:4, implementation: forward(instructions.ld_b_d)!),
            Instruction(opCode: 0x43, length: 1, name: "LD B, E", duration:4, implementation: forward(instructions.ld_b_e)!),
            Instruction(opCode: 0x44, length: 1, name: "LD B, H", duration:4, implementation: forward(instructions.ld_b_h)!),
            Instruction(opCode: 0x45, length: 1, name: "LD B, L", duration:4, implementation: forward(instructions.ld_b_l)!),
            Instruction(opCode: 0x46, length: 1, name: "LD B, (HL)", duration:8, implementation: forward(instructions.ld_b_hlp)!),
            Instruction(opCode: 0x47, length: 1, name: "LD B, A", duration:4, implementation: forward(instructions.ld_b_a)!),
            Instruction(opCode: 0x48, length: 1, name: "LD C, B", duration:4, implementation: forward(instructions.ld_c_b)!),
            Instruction(opCode: 0x49, length: 1, name: "LD C, C", duration:4, implementation: forward(instructions.ld_c_c)!),
            Instruction(opCode: 0x4A, length: 1, name: "LD C, D", duration:4, implementation: forward(instructions.ld_c_d)!),
            Instruction(opCode: 0x4B, length: 1, name: "LD C, E", duration:4, implementation: forward(instructions.ld_c_e)!),
            Instruction(opCode: 0x4C, length: 1, name: "LD C, H", duration:4, implementation: forward(instructions.ld_c_h)!),
            Instruction(opCode: 0x4D, length: 1, name: "LD C, L", duration:4, implementation: forward(instructions.ld_c_l)!),
            Instruction(opCode: 0x4E, length: 1, name: "LD C, (HL)", duration:8, implementation: forward(instructions.ld_c_hlp)!),
            Instruction(opCode: 0x4F, length: 1, name: "LD C, A", duration:4, implementation: forward(instructions.ld_c_a)!),
            Instruction(opCode: 0x50, length: 1, name: "LD D, B", duration:4, implementation: forward(instructions.ld_d_b)!),
            Instruction(opCode: 0x51, length: 1, name: "LD D, C", duration:4, implementation: forward(instructions.ld_d_c)!),
            Instruction(opCode: 0x52, length: 1, name: "LD D, D", duration:4, implementation: forward(instructions.ld_d_d)!),
            Instruction(opCode: 0x53, length: 1, name: "LD D, E", duration:4, implementation: forward(instructions.ld_d_e)!),
            Instruction(opCode: 0x54, length: 1, name: "LD D, H", duration:4, implementation: forward(instructions.ld_d_h)!),
            Instruction(opCode: 0x55, length: 1, name: "LD D, L", duration:4, implementation: forward(instructions.ld_d_l)!),
            Instruction(opCode: 0x56, length: 1, name: "LD D, (HL)", duration:8, implementation: forward(instructions.ld_d_hlp)!),
            Instruction(opCode: 0x57, length: 1, name: "LD D, A", duration:4, implementation: forward(instructions.ld_d_a)!),
            Instruction(opCode: 0x58, length: 1, name: "LD E, B", duration:4, implementation: forward(instructions.ld_e_b)!),
            Instruction(opCode: 0x59, length: 1, name: "LD E, C", duration:4, implementation: forward(instructions.ld_e_c)!),
            Instruction(opCode: 0x5A, length: 1, name: "LD E, D", duration:4, implementation: forward(instructions.ld_e_d)!),
            Instruction(opCode: 0x5B, length: 1, name: "LD E, E", duration:4, implementation: forward(instructions.ld_e_e)!),
            Instruction(opCode: 0x5C, length: 1, name: "LD E, H", duration:4, implementation: forward(instructions.ld_e_h)!),
            Instruction(opCode: 0x5D, length: 1, name: "LD E, L", duration:4, implementation: forward(instructions.ld_e_l)!),
            Instruction(opCode: 0x5E, length: 1, name: "LD E, (HL)", duration:8, implementation: forward(instructions.ld_e_hlp)!),
            Instruction(opCode: 0x5F, length: 1, name: "LD E, A", duration:4, implementation: forward(instructions.ld_e_a)!),
            Instruction(opCode: 0x60, length: 1, name: "LD H, B", duration:4, implementation: forward(instructions.ld_h_b)!),
            Instruction(opCode: 0x61, length: 1, name: "LD H, C", duration:4, implementation: forward(instructions.ld_h_c)!),
            Instruction(opCode: 0x62, length: 1, name: "LD H, D", duration:4, implementation: forward(instructions.ld_h_d)!),
            Instruction(opCode: 0x63, length: 1, name: "LD H, E", duration:4, implementation: forward(instructions.ld_h_e)!),
            Instruction(opCode: 0x64, length: 1, name: "LD H, H", duration:4, implementation: forward(instructions.ld_h_h)!),
            Instruction(opCode: 0x65, length: 1, name: "LD H, L", duration:4, implementation: forward(instructions.ld_h_l)!),
            Instruction(opCode: 0x66, length: 1, name: "LD H, (HL)", duration:8, implementation: forward(instructions.ld_h_hlp)!),
            Instruction(opCode: 0x67, length: 1, name: "LD H, A", duration:4, implementation: forward(instructions.ld_h_a)!),
            Instruction(opCode: 0x68, length: 1, name: "LD L, B", duration:4, implementation: forward(instructions.ld_l_b)!),
            Instruction(opCode: 0x69, length: 1, name: "LD L, C", duration:4, implementation: forward(instructions.ld_l_c)!),
            Instruction(opCode: 0x6A, length: 1, name: "LD L, D", duration:4, implementation: forward(instructions.ld_l_d)!),
            Instruction(opCode: 0x6B, length: 1, name: "LD L, E", duration:4, implementation: forward(instructions.ld_l_e)!),
            Instruction(opCode: 0x6C, length: 1, name: "LD L, H", duration:4, implementation: forward(instructions.ld_l_h)!),
            Instruction(opCode: 0x6D, length: 1, name: "LD L, L", duration:4, implementation: forward(instructions.ld_l_l)!),
            Instruction(opCode: 0x6E, length: 1, name: "LD L, (HL)", duration:8, implementation: forward(instructions.ld_l_hlp)!),
            Instruction(opCode: 0x6F, length: 1, name: "LD L, A", duration:4, implementation: forward(instructions.ld_l_a)!),
            Instruction(opCode: 0x70, length: 1, name: "LD (HL), B", duration:8, implementation: forward(instructions.ld_hlp_b)!),
            Instruction(opCode: 0x71, length: 1, name: "LD (HL), C", duration:8, implementation: forward(instructions.ld_hlp_c)!),
            Instruction(opCode: 0x72, length: 1, name: "LD (HL), D", duration:8, implementation: forward(instructions.ld_hlp_d)!),
            Instruction(opCode: 0x73, length: 1, name: "LD (HL), E", duration:8, implementation: forward(instructions.ld_hlp_e)!),
            Instruction(opCode: 0x74, length: 1, name: "LD (HL), H", duration:8, implementation: forward(instructions.ld_hlp_h)!),
            Instruction(opCode: 0x75, length: 1, name: "LD (HL), L", duration:8, implementation: forward(instructions.ld_hlp_l)!),
            // Instruction(opCode: 0x76, length: 1, name: "HALT", duration:4, implementation: forward(instructions.halt)!),
            Instruction(opCode: 0x77, length: 1, name: "LD (HL), A", duration:8, implementation: forward(instructions.ld_hlp_a)!),
            Instruction(opCode: 0x78, length: 1, name: "LD A, B", duration:4, implementation: forward(instructions.ld_a_b)!),
            Instruction(opCode: 0x79, length: 1, name: "LD A, C", duration:4, implementation: forward(instructions.ld_a_c)!),
            Instruction(opCode: 0x7A, length: 1, name: "LD A, D", duration:4, implementation: forward(instructions.ld_a_d)!),
            Instruction(opCode: 0x7B, length: 1, name: "LD A, E", duration:4, implementation: forward(instructions.ld_a_e)!),
            Instruction(opCode: 0x7C, length: 1, name: "LD A, H", duration:4, implementation: forward(instructions.ld_a_h)!),
            Instruction(opCode: 0x7D, length: 1, name: "LD A, L", duration:4, implementation: forward(instructions.ld_a_l)!),
            Instruction(opCode: 0x7E, length: 1, name: "LD A, (HL)", duration:8, implementation: forward(instructions.ld_a_hlp)!),
            Instruction(opCode: 0x7F, length: 1, name: "LD A, A", duration:4, implementation: forward(instructions.ld_a_a)!),
            Instruction(opCode: 0x80, length: 1, name: "ADD A, B", duration:4, implementation: forward(instructions.add_a_b)!),
            Instruction(opCode: 0x81, length: 1, name: "ADD A, C", duration:4, implementation: forward(instructions.add_a_c)!),
            Instruction(opCode: 0x82, length: 1, name: "ADD A, D", duration:4, implementation: forward(instructions.add_a_d)!),
            Instruction(opCode: 0x83, length: 1, name: "ADD A, E", duration:4, implementation: forward(instructions.add_a_e)!),
            Instruction(opCode: 0x84, length: 1, name: "ADD A, H", duration:4, implementation: forward(instructions.add_a_h)!),
            Instruction(opCode: 0x85, length: 1, name: "ADD A, L", duration:4, implementation: forward(instructions.add_a_l)!),
            Instruction(opCode: 0x86, length: 1, name: "ADD A, (HL)", duration:8, implementation: forward(instructions.add_a_hlp)!),
            Instruction(opCode: 0x87, length: 1, name: "ADD A, A", duration:4, implementation: forward(instructions.add_a_a)!),
            Instruction(opCode: 0x88, length: 1, name: "ADC A, B", duration:4, implementation: forward(instructions.adc_a_b)!),
            Instruction(opCode: 0x89, length: 1, name: "ADC A, C", duration:4, implementation: forward(instructions.adc_a_c)!),
            Instruction(opCode: 0x8A, length: 1, name: "ADC A, D", duration:4, implementation: forward(instructions.adc_a_d)!),
            Instruction(opCode: 0x8B, length: 1, name: "ADC A, E", duration:4, implementation: forward(instructions.adc_a_e)!),
            Instruction(opCode: 0x8C, length: 1, name: "ADC A, H", duration:4, implementation: forward(instructions.adc_a_h)!),
            Instruction(opCode: 0x8D, length: 1, name: "ADC A, L", duration:4, implementation: forward(instructions.adc_a_l)!),
            Instruction(opCode: 0x8E, length: 1, name: "ADC A, (HL)", duration:8, implementation: forward(instructions.adc_a_hlp)!),
            Instruction(opCode: 0x8F, length: 1, name: "ADC A, A", duration:4, implementation: forward(instructions.adc_a_a)!),
            Instruction(opCode: 0x90, length: 1, name: "SUB A, B", duration:4, implementation: forward(instructions.sub_a_b)!),
            Instruction(opCode: 0x91, length: 1, name: "SUB A, C", duration:4, implementation: forward(instructions.sub_a_c)!),
            Instruction(opCode: 0x92, length: 1, name: "SUB A, D", duration:4, implementation: forward(instructions.sub_a_d)!),
            Instruction(opCode: 0x93, length: 1, name: "SUB A, E", duration:4, implementation: forward(instructions.sub_a_e)!),
            Instruction(opCode: 0x94, length: 1, name: "SUB A, H", duration:4, implementation: forward(instructions.sub_a_h)!),
            Instruction(opCode: 0x95, length: 1, name: "SUB A, L", duration:4, implementation: forward(instructions.sub_a_l)!),
            Instruction(opCode: 0x96, length: 1, name: "SUB A, (HL)", duration:8, implementation: forward(instructions.sub_a_hlp)!),
            Instruction(opCode: 0x97, length: 1, name: "SUB A, A", duration:4, implementation: forward(instructions.sub_a_a)!),
            Instruction(opCode: 0x98, length: 1, name: "SBC A, B", duration:4, implementation: forward(instructions.sbc_a_b)!),
            Instruction(opCode: 0x99, length: 1, name: "SBC A, C", duration:4, implementation: forward(instructions.sbc_a_c)!),
            Instruction(opCode: 0x9A, length: 1, name: "SBC A, D", duration:4, implementation: forward(instructions.sbc_a_d)!),
            Instruction(opCode: 0x9B, length: 1, name: "SBC A, E", duration:4, implementation: forward(instructions.sbc_a_e)!),
            Instruction(opCode: 0x9C, length: 1, name: "SBC A, H", duration:4, implementation: forward(instructions.sbc_a_h)!),
            Instruction(opCode: 0x9D, length: 1, name: "SBC A, L", duration:4, implementation: forward(instructions.sbc_a_l)!),
            Instruction(opCode: 0x9E, length: 1, name: "SBC A, (HL)", duration:8, implementation: forward(instructions.sbc_a_hlp)!),
            Instruction(opCode: 0x9F, length: 1, name: "SBC A, A", duration:4, implementation: forward(instructions.sbc_a_a)!),
            Instruction(opCode: 0xA0, length: 1, name: "AND A, B", duration:4, implementation: forward(instructions.and_a_b)!),
            Instruction(opCode: 0xA1, length: 1, name: "AND A, C", duration:4, implementation: forward(instructions.and_a_c)!),
            Instruction(opCode: 0xA2, length: 1, name: "AND A, D", duration:4, implementation: forward(instructions.and_a_d)!),
            Instruction(opCode: 0xA3, length: 1, name: "AND A, E", duration:4, implementation: forward(instructions.and_a_e)!),
            Instruction(opCode: 0xA4, length: 1, name: "AND A, H", duration:4, implementation: forward(instructions.and_a_h)!),
            Instruction(opCode: 0xA5, length: 1, name: "AND A, L", duration:4, implementation: forward(instructions.and_a_l)!),
            Instruction(opCode: 0xA6, length: 1, name: "AND A, (HL)", duration:8, implementation: forward(instructions.and_a_hlp)!),
            Instruction(opCode: 0xA7, length: 1, name: "AND A, A", duration:4, implementation: forward(instructions.and_a_a)!),
            Instruction(opCode: 0xA8, length: 1, name: "XOR A, B", duration:4, implementation: forward(instructions.xor_a_b)!),
            Instruction(opCode: 0xA9, length: 1, name: "XOR A, C", duration:4, implementation: forward(instructions.xor_a_c)!),
            Instruction(opCode: 0xAA, length: 1, name: "XOR A, D", duration:4, implementation: forward(instructions.xor_a_d)!),
            Instruction(opCode: 0xAB, length: 1, name: "XOR A, E", duration:4, implementation: forward(instructions.xor_a_e)!),
            Instruction(opCode: 0xAC, length: 1, name: "XOR A, H", duration:4, implementation: forward(instructions.xor_a_h)!),
            Instruction(opCode: 0xAD, length: 1, name: "XOR A, L", duration:4, implementation: forward(instructions.xor_a_l)!),
            Instruction(opCode: 0xAE, length: 1, name: "XOR A, (HL)", duration:8, implementation: forward(instructions.xor_a_hlp)!),
            Instruction(opCode: 0xAF, length: 1, name: "XOR A, A", duration:4, implementation: forward(instructions.xor_a_a)!),
            Instruction(opCode: 0xB0, length: 1, name: "OR A, B", duration:4, implementation: forward(instructions.or_a_b)!),
            Instruction(opCode: 0xB1, length: 1, name: "OR A, C", duration:4, implementation: forward(instructions.or_a_c)!),
            Instruction(opCode: 0xB2, length: 1, name: "OR A, D", duration:4, implementation: forward(instructions.or_a_d)!),
            Instruction(opCode: 0xB3, length: 1, name: "OR A, E", duration:4, implementation: forward(instructions.or_a_e)!),
            Instruction(opCode: 0xB4, length: 1, name: "OR A, H", duration:4, implementation: forward(instructions.or_a_h)!),
            Instruction(opCode: 0xB5, length: 1, name: "OR A, L", duration:4, implementation: forward(instructions.or_a_l)!),
            Instruction(opCode: 0xB6, length: 1, name: "OR A, (HL)", duration:8, implementation: forward(instructions.or_a_hlp)!),
            Instruction(opCode: 0xB7, length: 1, name: "OR A, A", duration:4, implementation: forward(instructions.or_a_a)!),
            Instruction(opCode: 0xB8, length: 1, name: "CP A, B", duration:4, implementation: forward(instructions.cp_a_b)!),
            Instruction(opCode: 0xB9, length: 1, name: "CP A, C", duration:4, implementation: forward(instructions.cp_a_c)!),
            Instruction(opCode: 0xBA, length: 1, name: "CP A, D", duration:4, implementation: forward(instructions.cp_a_d)!),
            Instruction(opCode: 0xBB, length: 1, name: "CP A, E", duration:4, implementation: forward(instructions.cp_a_e)!),
            Instruction(opCode: 0xBC, length: 1, name: "CP A, H", duration:4, implementation: forward(instructions.cp_a_h)!),
            Instruction(opCode: 0xBD, length: 1, name: "CP A, L", duration:4, implementation: forward(instructions.cp_a_l)!),
            Instruction(opCode: 0xBE, length: 1, name: "CP A, (HL)", duration:8, implementation: forward(instructions.cp_a_hlp)!),
            Instruction(opCode: 0xBF, length: 1, name: "CP A, A", duration:4, implementation: forward(instructions.cp_a_a)!),
            Instruction(opCode: 0xC0, length: 1, name: "RET NZ", duration:8, implementation: forward(instructions.ret_nz)!),
            Instruction(opCode: 0xC1, length: 1, name: "POP BC", duration:12, implementation: forward(instructions.pop_bc)!),
            Instruction(opCode: 0xC2, length: 3, name: "JP NZ, 0x%04X", duration:12, implementation: forward(instructions.jp_nz_nn)!),
            Instruction(opCode: 0xC3, length: 3, name: "JP 0x%04X", duration:16, implementation: forward(instructions.jp_nn)!),
            Instruction(opCode: 0xC4, length: 3, name: "CALL NZ, 0x%04X", duration:12, implementation: forward(instructions.call_nz_nn)!),
            Instruction(opCode: 0xC5, length: 1, name: "PUSH BC", duration:16, implementation: forward(instructions.push_bc)!),
            Instruction(opCode: 0xC6, length: 2, name: "ADD A, 0x%02X", duration:8, implementation: forward(instructions.add_a_n)!),
            Instruction(opCode: 0xC7, length: 1, name: "RST 00h", duration:16, implementation: forward(instructions.rst_00h)!),
            Instruction(opCode: 0xC8, length: 1, name: "RET Z", duration:8, implementation: forward(instructions.ret_z)!),
            Instruction(opCode: 0xC9, length: 1, name: "RET", duration:16, implementation: forward(instructions.ret)!),
            Instruction(opCode: 0xCA, length: 3, name: "JP Z, 0x%04X", duration:12, implementation: forward(instructions.jp_z_nn)!),
            Instruction(opCode: 0xCC, length: 3, name: "CALL Z, 0x%04X", duration:12, implementation: forward(instructions.call_z_nn)!),
            Instruction(opCode: 0xCD, length: 3, name: "CALL 0x%04X", duration:24, implementation: forward(instructions.call_nn)!),
            Instruction(opCode: 0xCE, length: 2, name: "ADC A, 0x%02X", duration:8, implementation: forward(instructions.adc_a_n)!),
            Instruction(opCode: 0xCF, length: 1, name: "RST 08h", duration:16, implementation: forward(instructions.rst_08h)!),
            Instruction(opCode: 0xD0, length: 1, name: "RET NC", duration:8, implementation: forward(instructions.ret_nc)!),
            Instruction(opCode: 0xD1, length: 1, name: "POP DE", duration:12, implementation: forward(instructions.pop_de)!),
            Instruction(opCode: 0xD2, length: 3, name: "JP NC, 0x%04X", duration:12, implementation: forward(instructions.jp_nc_nn)!),
            Instruction(opCode: 0xD4, length: 3, name: "CALL NC, 0x%04X", duration:12, implementation: forward(instructions.call_nc_nn)!),
            Instruction(opCode: 0xD5, length: 1, name: "PUSH DE", duration:16, implementation: forward(instructions.push_de)!),
            Instruction(opCode: 0xD6, length: 2, name: "SUB A, 0x%02X", duration:8, implementation: forward(instructions.sub_a_n)!),
            Instruction(opCode: 0xD7, length: 1, name: "RST 10h", duration:16, implementation: forward(instructions.rst_10h)!),
            Instruction(opCode: 0xD8, length: 1, name: "RET C", duration:8, implementation: forward(instructions.ret_c)!),
            Instruction(opCode: 0xD9, length: 1, name: "RETI", duration:16, implementation: forward(instructions.reti)!),
            Instruction(opCode: 0xDA, length: 3, name: "JP C, 0x%04X", duration:12, implementation: forward(instructions.jp_c_nn)!),
            Instruction(opCode: 0xDC, length: 3, name: "CALL C, 0x%04X", duration:12, implementation: forward(instructions.call_c_nn)!),
            Instruction(opCode: 0xDE, length: 2, name: "SBC A, 0x%02X", duration:8, implementation: forward(instructions.sbc_a_n)!),
            Instruction(opCode: 0xDF, length: 1, name: "RST 18h", duration:16, implementation: forward(instructions.rst_18h)!),
            Instruction(opCode: 0xE0, length: 2, name: "LD (FF00+0x%02X) A", duration:12, implementation: forward(instructions.ld_ff00pn_a)!),
            Instruction(opCode: 0xE1, length: 1, name: "POP HL", duration:12, implementation: forward(instructions.pop_hl)!),
            Instruction(opCode: 0xE2, length: 1, name: "LD (FF00+C), A", duration:8, implementation: forward(instructions.ld_ff00pc_a)!),
            Instruction(opCode: 0xE5, length: 1, name: "PUSH HL", duration:16, implementation: forward(instructions.push_hl)!),
            Instruction(opCode: 0xE6, length: 2, name: "AND A, 0x%02X", duration:8, implementation: forward(instructions.and_a_n)!),
            Instruction(opCode: 0xE7, length: 1, name: "RST 20h", duration:16, implementation: forward(instructions.rst_20h)!),
            Instruction(opCode: 0xE8, length: 2, name: "ADD SP, 0x%02X", duration:16, implementation: forward(instructions.add_sp_n)!),
            Instruction(opCode: 0xE9, length: 1, name: "JP HL", duration:4, implementation: forward(instructions.jp_hl)!),
            Instruction(opCode: 0xEA, length: 3, name: "LD 0x%04X, A", duration:16, implementation: forward(instructions.ld_nnp_a)!),
            Instruction(opCode: 0xEE, length: 2, name: "XOR A, 0x%02X", duration:8, implementation: forward(instructions.xor_a_n)!),
            Instruction(opCode: 0xEF, length: 1, name: "RST 28h", duration:16, implementation: forward(instructions.rst_28h)!),
            Instruction(opCode: 0xF0, length: 2, name: "LD A, (FF00+0x%02X)", duration:12, implementation: forward(instructions.ld_a_ff00pn)!),
            Instruction(opCode: 0xF1, length: 1, name: "POP AF", duration:12, implementation: forward(instructions.pop_af)!),
            Instruction(opCode: 0xF2, length: 1, name: "LD A FF00+C", duration:8, implementation: forward(instructions.ld_a_ff00pc)!),
            Instruction(opCode: 0xF3, length: 1, name: "DI", duration:4, implementation: forward(instructions.di)!),
            Instruction(opCode: 0xF5, length: 1, name: "PUSH AF", duration:16, implementation: forward(instructions.push_af)!),
            Instruction(opCode: 0xF6, length: 2, name: "OR A, 0x%02X", duration:8, implementation: forward(instructions.or_a_n)!),
            Instruction(opCode: 0xF7, length: 1, name: "RST 30h", duration:16, implementation: forward(instructions.rst_30h)!),
            Instruction(opCode: 0xF8, length: 2, name: "LD HL, SP+0x%02X", duration:12, implementation: forward(instructions.ld_hl_sppn)!),
            Instruction(opCode: 0xF9, length: 1, name: "LD SP, HL", duration:8, implementation: forward(instructions.ld_sp_hl)!),
            Instruction(opCode: 0xFA, length: 3, name: "LD A, (0x%04X)", duration:16, implementation: forward(instructions.ld_a_nnp)!),
            Instruction(opCode: 0xFB, length: 1, name: "EI", duration:4, implementation: forward(instructions.ei)!),
            Instruction(opCode: 0xFE, length: 2, name: "CP A, 0x%02X", duration:8, implementation: forward(instructions.cp_a_n)!),
            Instruction(opCode: 0xFF, length: 1, name: "RST 38h", duration:16, implementation: forward(instructions.rst_38h)!),
        ]
    }
    
    /// build standard instruction array from an ExtendedInstructionSet implementation
    private func buildExtendedInstructionSet(instructions:ExtendedInstructionSet) -> [Instruction] {
        return [
            Instruction(opCode: 0x00, length: 1, name: "RLC B", duration:8, implementation: forward(instructions.rlc_b)!),
            Instruction(opCode: 0x01, length: 1, name: "RLC C", duration:8, implementation: forward(instructions.rlc_c)!),
            Instruction(opCode: 0x02, length: 1, name: "RLC D", duration:8, implementation: forward(instructions.rlc_d)!),
            Instruction(opCode: 0x03, length: 1, name: "RLC E", duration:8, implementation: forward(instructions.rlc_e)!),
            Instruction(opCode: 0x04, length: 1, name: "RLC H", duration:8, implementation: forward(instructions.rlc_h)!),
            Instruction(opCode: 0x05, length: 1, name: "RLC L", duration:8, implementation: forward(instructions.rlc_l)!),
            Instruction(opCode: 0x06, length: 1, name: "RLC (HL)", duration:16, implementation: forward(instructions.rlc_hlp)!),
            Instruction(opCode: 0x07, length: 1, name: "RLC A", duration:8, implementation: forward(instructions.rlc_a)!),
            Instruction(opCode: 0x08, length: 1, name: "RRC B", duration:8, implementation: forward(instructions.rrc_b)!),
            Instruction(opCode: 0x09, length: 1, name: "RRC C", duration:8, implementation: forward(instructions.rrc_c)!),
            Instruction(opCode: 0x0A, length: 1, name: "RRC D", duration:8, implementation: forward(instructions.rrc_d)!),
            Instruction(opCode: 0x0B, length: 1, name: "RRC E", duration:8, implementation: forward(instructions.rrc_e)!),
            Instruction(opCode: 0x0C, length: 1, name: "RRC H", duration:8, implementation: forward(instructions.rrc_h)!),
            Instruction(opCode: 0x0D, length: 1, name: "RRC L", duration:8, implementation: forward(instructions.rrc_l)!),
            Instruction(opCode: 0x0E, length: 1, name: "RRC (HL)", duration:16, implementation: forward(instructions.rrc_hlp)!),
            Instruction(opCode: 0x0F, length: 1, name: "RRC A", duration:8, implementation: forward(instructions.rrc_a)!),
            Instruction(opCode: 0x10, length: 1, name: "RL B", duration:8, implementation: forward(instructions.rl_b)!),
            Instruction(opCode: 0x11, length: 1, name: "RL C", duration:8, implementation: forward(instructions.rl_c)!),
            Instruction(opCode: 0x12, length: 1, name: "RL D", duration:8, implementation: forward(instructions.rl_d)!),
            Instruction(opCode: 0x13, length: 1, name: "RL E", duration:8, implementation: forward(instructions.rl_e)!),
            Instruction(opCode: 0x14, length: 1, name: "RL H", duration:8, implementation: forward(instructions.rl_h)!),
            Instruction(opCode: 0x15, length: 1, name: "RL L", duration:8, implementation: forward(instructions.rl_l)!),
            Instruction(opCode: 0x16, length: 1, name: "RL (HL)", duration:16, implementation: forward(instructions.rl_hlp)!),
            Instruction(opCode: 0x17, length: 1, name: "RL A", duration:8, implementation: forward(instructions.rl_a)!),
            Instruction(opCode: 0x18, length: 1, name: "RR B", duration:8, implementation: forward(instructions.rr_b)!),
            Instruction(opCode: 0x19, length: 1, name: "RR C", duration:8, implementation: forward(instructions.rr_c)!),
            Instruction(opCode: 0x1A, length: 1, name: "RR D", duration:8, implementation: forward(instructions.rr_d)!),
            Instruction(opCode: 0x1B, length: 1, name: "RR E", duration:8, implementation: forward(instructions.rr_e)!),
            Instruction(opCode: 0x1C, length: 1, name: "RR H", duration:8, implementation: forward(instructions.rr_h)!),
            Instruction(opCode: 0x1D, length: 1, name: "RR L", duration:8, implementation: forward(instructions.rr_l)!),
            Instruction(opCode: 0x1E, length: 1, name: "RR (HL)", duration:16, implementation: forward(instructions.rr_hlp)!),
            Instruction(opCode: 0x1F, length: 1, name: "RR A", duration:8, implementation: forward(instructions.rr_a)!),
            //Instruction(opCode: 0x20, length: 1, name: "SLA B", duration:8, implementation: forward(instructions.sla_b)!),
            //Instruction(opCode: 0x21, length: 1, name: "SLA C", duration:8, implementation: forward(instructions.sla_c)!),
            //Instruction(opCode: 0x22, length: 1, name: "SLA D", duration:8, implementation: forward(instructions.sla_d)!),
            //Instruction(opCode: 0x23, length: 1, name: "SLA E", duration:8, implementation: forward(instructions.sla_e)!),
            //Instruction(opCode: 0x24, length: 1, name: "SLA H", duration:8, implementation: forward(instructions.sla_h)!),
            //Instruction(opCode: 0x25, length: 1, name: "SLA L", duration:8, implementation: forward(instructions.sla_l)!),
            //Instruction(opCode: 0x26, length: 1, name: "SLA (HL)", duration:16, implementation: forward(instructions.sla_hlp)!),
            //Instruction(opCode: 0x27, length: 1, name: "SLA A", duration:8, implementation: forward(instructions.sla_a)!),
            //Instruction(opCode: 0x28, length: 1, name: "SRA B", duration:8, implementation: forward(instructions.sra_b)!),
            //Instruction(opCode: 0x29, length: 1, name: "SRA C", duration:8, implementation: forward(instructions.sra_c)!),
            //Instruction(opCode: 0x2A, length: 1, name: "SRA D", duration:8, implementation: forward(instructions.sra_d)!),
            //Instruction(opCode: 0x2B, length: 1, name: "SRA E", duration:8, implementation: forward(instructions.sra_e)!),
            //Instruction(opCode: 0x2C, length: 1, name: "SRA H", duration:8, implementation: forward(instructions.sra_h)!),
            //Instruction(opCode: 0x2D, length: 1, name: "SRA L", duration:8, implementation: forward(instructions.sra_l)!),
            //Instruction(opCode: 0x2E, length: 1, name: "SRA (HL)", duration:16, implementation: forward(instructions.sra_hlp)!),
            //Instruction(opCode: 0x2F, length: 1, name: "SRA A", duration:8, implementation: forward(instructions.sra_a)!),
            Instruction(opCode: 0x30, length: 1, name: "SWAP B", duration:8, implementation: forward(instructions.swap_b)!),
            Instruction(opCode: 0x31, length: 1, name: "SWAP C", duration:8, implementation: forward(instructions.swap_c)!),
            Instruction(opCode: 0x32, length: 1, name: "SWAP D", duration:8, implementation: forward(instructions.swap_d)!),
            Instruction(opCode: 0x33, length: 1, name: "SWAP E", duration:8, implementation: forward(instructions.swap_e)!),
            Instruction(opCode: 0x34, length: 1, name: "SWAP H", duration:8, implementation: forward(instructions.swap_h)!),
            Instruction(opCode: 0x35, length: 1, name: "SWAP L", duration:8, implementation: forward(instructions.swap_l)!),
            Instruction(opCode: 0x36, length: 1, name: "SWAP (HL)", duration:16, implementation: forward(instructions.swap_hlp)!),
            Instruction(opCode: 0x37, length: 1, name: "SWAP A", duration:8, implementation: forward(instructions.swap_a)!),
            //Instruction(opCode: 0x38, length: 1, name: "SRL B", duration:8, implementation: forward(instructions.srl_b)!),
            //Instruction(opCode: 0x39, length: 1, name: "SRL C", duration:8, implementation: forward(instructions.srl_c)!),
            //Instruction(opCode: 0x3A, length: 1, name: "SRL D", duration:8, implementation: forward(instructions.srl_d)!),
            //Instruction(opCode: 0x3B, length: 1, name: "SRL E", duration:8, implementation: forward(instructions.srl_e)!),
            //Instruction(opCode: 0x3C, length: 1, name: "SRL H", duration:8, implementation: forward(instructions.srl_h)!),
            //Instruction(opCode: 0x3D, length: 1, name: "SRL L", duration:8, implementation: forward(instructions.srl_l)!),
            //Instruction(opCode: 0x3E, length: 1, name: "SRL (HL)", duration:16, implementation: forward(instructions.srl_hlp)!),
            //Instruction(opCode: 0x3F, length: 1, name: "SRL A", duration:8, implementation: forward(instructions.srl_a)!),
            Instruction(opCode: 0x40, length: 1, name: "BIT 0, B", duration:8, implementation: forward(instructions.bit_0_b)!),
            Instruction(opCode: 0x41, length: 1, name: "BIT 0, C", duration:8, implementation: forward(instructions.bit_0_c)!),
            Instruction(opCode: 0x42, length: 1, name: "BIT 0, D", duration:8, implementation: forward(instructions.bit_0_d)!),
            Instruction(opCode: 0x43, length: 1, name: "BIT 0, E", duration:8, implementation: forward(instructions.bit_0_e)!),
            Instruction(opCode: 0x44, length: 1, name: "BIT 0, H", duration:8, implementation: forward(instructions.bit_0_h)!),
            Instruction(opCode: 0x45, length: 1, name: "BIT 0, L", duration:8, implementation: forward(instructions.bit_0_l)!),
            Instruction(opCode: 0x46, length: 1, name: "BIT 0, (HL)", duration:12, implementation: forward(instructions.bit_0_hlp)!),
            Instruction(opCode: 0x47, length: 1, name: "BIT 0, A", duration:8, implementation: forward(instructions.bit_0_a)!),
            Instruction(opCode: 0x48, length: 1, name: "BIT 1, B", duration:8, implementation: forward(instructions.bit_1_b)!),
            Instruction(opCode: 0x49, length: 1, name: "BIT 1, C", duration:8, implementation: forward(instructions.bit_1_c)!),
            Instruction(opCode: 0x4A, length: 1, name: "BIT 1, D", duration:8, implementation: forward(instructions.bit_1_d)!),
            Instruction(opCode: 0x4B, length: 1, name: "BIT 1, E", duration:8, implementation: forward(instructions.bit_1_e)!),
            Instruction(opCode: 0x4C, length: 1, name: "BIT 1, H", duration:8, implementation: forward(instructions.bit_1_h)!),
            Instruction(opCode: 0x4D, length: 1, name: "BIT 1, L", duration:8, implementation: forward(instructions.bit_1_l)!),
            Instruction(opCode: 0x4E, length: 1, name: "BIT 1, (HL)", duration:12, implementation: forward(instructions.bit_1_hlp)!),
            Instruction(opCode: 0x4F, length: 1, name: "BIT 1, A", duration:8, implementation: forward(instructions.bit_1_a)!),
            Instruction(opCode: 0x50, length: 1, name: "BIT 2, B", duration:8, implementation: forward(instructions.bit_2_b)!),
            Instruction(opCode: 0x51, length: 1, name: "BIT 2, C", duration:8, implementation: forward(instructions.bit_2_c)!),
            Instruction(opCode: 0x52, length: 1, name: "BIT 2, D", duration:8, implementation: forward(instructions.bit_2_d)!),
            Instruction(opCode: 0x53, length: 1, name: "BIT 2, E", duration:8, implementation: forward(instructions.bit_2_e)!),
            Instruction(opCode: 0x54, length: 1, name: "BIT 2, H", duration:8, implementation: forward(instructions.bit_2_h)!),
            Instruction(opCode: 0x55, length: 1, name: "BIT 2, L", duration:8, implementation: forward(instructions.bit_2_l)!),
            Instruction(opCode: 0x56, length: 1, name: "BIT 2, (HL)", duration:12, implementation: forward(instructions.bit_2_hlp)!),
            Instruction(opCode: 0x57, length: 1, name: "BIT 2, A", duration:8, implementation: forward(instructions.bit_2_a)!),
            Instruction(opCode: 0x58, length: 1, name: "BIT 3, B", duration:8, implementation: forward(instructions.bit_3_b)!),
            Instruction(opCode: 0x59, length: 1, name: "BIT 3, C", duration:8, implementation: forward(instructions.bit_3_c)!),
            Instruction(opCode: 0x5A, length: 1, name: "BIT 3, D", duration:8, implementation: forward(instructions.bit_3_d)!),
            Instruction(opCode: 0x5B, length: 1, name: "BIT 3, E", duration:8, implementation: forward(instructions.bit_3_e)!),
            Instruction(opCode: 0x5C, length: 1, name: "BIT 3, H", duration:8, implementation: forward(instructions.bit_3_h)!),
            Instruction(opCode: 0x5D, length: 1, name: "BIT 3, L", duration:8, implementation: forward(instructions.bit_3_l)!),
            Instruction(opCode: 0x5E, length: 1, name: "BIT 3, (HL)", duration:12, implementation: forward(instructions.bit_3_hlp)!),
            Instruction(opCode: 0x5F, length: 1, name: "BIT 3, A", duration:8, implementation: forward(instructions.bit_3_a)!),
            Instruction(opCode: 0x60, length: 1, name: "BIT 4, B", duration:8, implementation: forward(instructions.bit_4_b)!),
            Instruction(opCode: 0x61, length: 1, name: "BIT 4, C", duration:8, implementation: forward(instructions.bit_4_c)!),
            Instruction(opCode: 0x62, length: 1, name: "BIT 4, D", duration:8, implementation: forward(instructions.bit_4_d)!),
            Instruction(opCode: 0x63, length: 1, name: "BIT 4, E", duration:8, implementation: forward(instructions.bit_4_e)!),
            Instruction(opCode: 0x64, length: 1, name: "BIT 4, H", duration:8, implementation: forward(instructions.bit_4_h)!),
            Instruction(opCode: 0x65, length: 1, name: "BIT 4, L", duration:8, implementation: forward(instructions.bit_4_l)!),
            Instruction(opCode: 0x66, length: 1, name: "BIT 4, (HL)", duration:12, implementation: forward(instructions.bit_4_hlp)!),
            Instruction(opCode: 0x67, length: 1, name: "BIT 4, A", duration:8, implementation: forward(instructions.bit_4_a)!),
            Instruction(opCode: 0x68, length: 1, name: "BIT 5, B", duration:8, implementation: forward(instructions.bit_5_b)!),
            Instruction(opCode: 0x69, length: 1, name: "BIT 5, C", duration:8, implementation: forward(instructions.bit_5_c)!),
            Instruction(opCode: 0x6A, length: 1, name: "BIT 5, D", duration:8, implementation: forward(instructions.bit_5_d)!),
            Instruction(opCode: 0x6B, length: 1, name: "BIT 5, E", duration:8, implementation: forward(instructions.bit_5_e)!),
            Instruction(opCode: 0x6C, length: 1, name: "BIT 6, H", duration:8, implementation: forward(instructions.bit_5_h)!),
            Instruction(opCode: 0x6D, length: 1, name: "BIT 6, L", duration:8, implementation: forward(instructions.bit_5_l)!),
            Instruction(opCode: 0x6E, length: 1, name: "BIT 5, (HL)", duration:12, implementation: forward(instructions.bit_5_hlp)!),
            Instruction(opCode: 0x6F, length: 1, name: "BIT 5, A", duration:8, implementation: forward(instructions.bit_5_a)!),
            Instruction(opCode: 0x70, length: 1, name: "BIT 6, B", duration:8, implementation: forward(instructions.bit_6_b)!),
            Instruction(opCode: 0x71, length: 1, name: "BIT 6, C", duration:8, implementation: forward(instructions.bit_6_c)!),
            Instruction(opCode: 0x72, length: 1, name: "BIT 6, D", duration:8, implementation: forward(instructions.bit_6_d)!),
            Instruction(opCode: 0x73, length: 1, name: "BIT 6, E", duration:8, implementation: forward(instructions.bit_6_e)!),
            Instruction(opCode: 0x74, length: 1, name: "BIT 6, H", duration:8, implementation: forward(instructions.bit_6_h)!),
            Instruction(opCode: 0x75, length: 1, name: "BIT 6, L", duration:8, implementation: forward(instructions.bit_6_l)!),
            Instruction(opCode: 0x76, length: 1, name: "BIT 6, (HL)", duration:12, implementation: forward(instructions.bit_6_hlp)!),
            Instruction(opCode: 0x77, length: 1, name: "BIT 6, A", duration:8, implementation: forward(instructions.bit_6_a)!),
            Instruction(opCode: 0x78, length: 1, name: "BIT 7, B", duration:8, implementation: forward(instructions.bit_7_b)!),
            Instruction(opCode: 0x79, length: 1, name: "BIT 7, C", duration:8, implementation: forward(instructions.bit_7_c)!),
            Instruction(opCode: 0x7A, length: 1, name: "BIT 7, D", duration:8, implementation: forward(instructions.bit_7_d)!),
            Instruction(opCode: 0x7B, length: 1, name: "BIT 7, E", duration:8, implementation: forward(instructions.bit_7_e)!),
            Instruction(opCode: 0x7C, length: 1, name: "BIT 7, H", duration:8, implementation: forward(instructions.bit_7_h)!),
            Instruction(opCode: 0x7D, length: 1, name: "BIT 7, L", duration:8, implementation: forward(instructions.bit_7_l)!),
            Instruction(opCode: 0x7E, length: 1, name: "BIT 7, (HL)", duration:12, implementation: forward(instructions.bit_7_hlp)!),
            Instruction(opCode: 0x7F, length: 1, name: "BIT 7, A", duration:8, implementation: forward(instructions.bit_7_a)!),
            Instruction(opCode: 0x80, length: 1, name: "RES 0, B", duration:8, implementation: forward(instructions.res_0_b)!),
            Instruction(opCode: 0x81, length: 1, name: "RES 0, C", duration:8, implementation: forward(instructions.res_0_c)!),
            Instruction(opCode: 0x82, length: 1, name: "RES 0, D", duration:8, implementation: forward(instructions.res_0_d)!),
            Instruction(opCode: 0x83, length: 1, name: "RES 0, E", duration:8, implementation: forward(instructions.res_0_e)!),
            Instruction(opCode: 0x84, length: 1, name: "RES 0, H", duration:8, implementation: forward(instructions.res_0_h)!),
            Instruction(opCode: 0x85, length: 1, name: "RES 0, L", duration:8, implementation: forward(instructions.res_0_l)!),
            Instruction(opCode: 0x86, length: 1, name: "RES 0, (HL)", duration:16, implementation: forward(instructions.res_0_hlp)!),
            Instruction(opCode: 0x87, length: 1, name: "RES 0, A", duration:8, implementation: forward(instructions.res_0_a)!),
            Instruction(opCode: 0x88, length: 1, name: "RES 1, B", duration:8, implementation: forward(instructions.res_1_b)!),
            Instruction(opCode: 0x89, length: 1, name: "RES 1, C", duration:8, implementation: forward(instructions.res_1_c)!),
            Instruction(opCode: 0x8A, length: 1, name: "RES 1, D", duration:8, implementation: forward(instructions.res_1_d)!),
            Instruction(opCode: 0x8B, length: 1, name: "RES 1, E", duration:8, implementation: forward(instructions.res_1_e)!),
            Instruction(opCode: 0x8C, length: 1, name: "RES 1, H", duration:8, implementation: forward(instructions.res_1_h)!),
            Instruction(opCode: 0x8D, length: 1, name: "RES 1, L", duration:8, implementation: forward(instructions.res_1_l)!),
            Instruction(opCode: 0x8E, length: 1, name: "RES 1, (HL)", duration:16, implementation: forward(instructions.res_1_hlp)!),
            Instruction(opCode: 0x8F, length: 1, name: "RES 1, A", duration:8, implementation: forward(instructions.res_1_a)!),
            Instruction(opCode: 0x90, length: 1, name: "RES 2, B", duration:8, implementation: forward(instructions.res_2_b)!),
            Instruction(opCode: 0x91, length: 1, name: "RES 2, C", duration:8, implementation: forward(instructions.res_2_c)!),
            Instruction(opCode: 0x92, length: 1, name: "RES 2, D", duration:8, implementation: forward(instructions.res_2_d)!),
            Instruction(opCode: 0x93, length: 1, name: "RES 2, E", duration:8, implementation: forward(instructions.res_2_e)!),
            Instruction(opCode: 0x94, length: 1, name: "RES 2, H", duration:8, implementation: forward(instructions.res_2_h)!),
            Instruction(opCode: 0x95, length: 1, name: "RES 2, L", duration:8, implementation: forward(instructions.res_2_l)!),
            Instruction(opCode: 0x96, length: 1, name: "RES 2, (HL)", duration:16, implementation: forward(instructions.res_2_hlp)!),
            Instruction(opCode: 0x97, length: 1, name: "RES 2, A", duration:8, implementation: forward(instructions.res_2_a)!),
            Instruction(opCode: 0x98, length: 1, name: "RES 3, B", duration:8, implementation: forward(instructions.res_3_b)!),
            Instruction(opCode: 0x99, length: 1, name: "RES 3, C", duration:8, implementation: forward(instructions.res_3_c)!),
            Instruction(opCode: 0x9A, length: 1, name: "RES 3, D", duration:8, implementation: forward(instructions.res_3_d)!),
            Instruction(opCode: 0x9B, length: 1, name: "RES 3, E", duration:8, implementation: forward(instructions.res_3_e)!),
            Instruction(opCode: 0x9C, length: 1, name: "RES 3, H", duration:8, implementation: forward(instructions.res_3_h)!),
            Instruction(opCode: 0x9D, length: 1, name: "RES 3, L", duration:8, implementation: forward(instructions.res_3_l)!),
            Instruction(opCode: 0x9E, length: 1, name: "RES 3, (HL)", duration:16, implementation: forward(instructions.res_3_hlp)!),
            Instruction(opCode: 0x9F, length: 1, name: "RES 3, A", duration:8, implementation: forward(instructions.res_3_a)!),
            Instruction(opCode: 0xA0, length: 1, name: "RES 4, B", duration:8, implementation: forward(instructions.res_4_b)!),
            Instruction(opCode: 0xA1, length: 1, name: "RES 4, C", duration:8, implementation: forward(instructions.res_4_c)!),
            Instruction(opCode: 0xA2, length: 1, name: "RES 4, D", duration:8, implementation: forward(instructions.res_4_d)!),
            Instruction(opCode: 0xA3, length: 1, name: "RES 4, E", duration:8, implementation: forward(instructions.res_4_e)!),
            Instruction(opCode: 0xA4, length: 1, name: "RES 4, H", duration:8, implementation: forward(instructions.res_4_h)!),
            Instruction(opCode: 0xA5, length: 1, name: "RES 4, L", duration:8, implementation: forward(instructions.res_4_l)!),
            Instruction(opCode: 0xA6, length: 1, name: "RES 4, (HL)", duration:16, implementation: forward(instructions.res_4_hlp)!),
            Instruction(opCode: 0xA7, length: 1, name: "RES 4, A", duration:8, implementation: forward(instructions.res_4_a)!),
            Instruction(opCode: 0xA8, length: 1, name: "RES 5, B", duration:8, implementation: forward(instructions.res_5_b)!),
            Instruction(opCode: 0xA9, length: 1, name: "RES 5, C", duration:8, implementation: forward(instructions.res_5_c)!),
            Instruction(opCode: 0xAA, length: 1, name: "RES 5, D", duration:8, implementation: forward(instructions.res_5_d)!),
            Instruction(opCode: 0xAB, length: 1, name: "RES 5, E", duration:8, implementation: forward(instructions.res_5_e)!),
            Instruction(opCode: 0xAC, length: 1, name: "RES 5, H", duration:8, implementation: forward(instructions.res_5_h)!),
            Instruction(opCode: 0xAD, length: 1, name: "RES 5, L", duration:8, implementation: forward(instructions.res_5_l)!),
            Instruction(opCode: 0xAE, length: 1, name: "RES 5, (HL)", duration:16, implementation: forward(instructions.res_5_hlp)!),
            Instruction(opCode: 0xAF, length: 1, name: "RES 5, A", duration:8, implementation: forward(instructions.res_5_a)!),
            Instruction(opCode: 0xB0, length: 1, name: "RES 6, B", duration:8, implementation: forward(instructions.res_6_b)!),
            Instruction(opCode: 0xB1, length: 1, name: "RES 6, C", duration:8, implementation: forward(instructions.res_6_c)!),
            Instruction(opCode: 0xB2, length: 1, name: "RES 6, D", duration:8, implementation: forward(instructions.res_6_d)!),
            Instruction(opCode: 0xB3, length: 1, name: "RES 6, E", duration:8, implementation: forward(instructions.res_6_e)!),
            Instruction(opCode: 0xB4, length: 1, name: "RES 6, H", duration:8, implementation: forward(instructions.res_6_h)!),
            Instruction(opCode: 0xB5, length: 1, name: "RES 6, L", duration:8, implementation: forward(instructions.res_6_l)!),
            Instruction(opCode: 0xB6, length: 1, name: "RES 6, (HL)", duration:16, implementation: forward(instructions.res_6_hlp)!),
            Instruction(opCode: 0xB7, length: 1, name: "RES 6, A", duration:8, implementation: forward(instructions.res_6_a)!),
            Instruction(opCode: 0xB8, length: 1, name: "RES 7, B", duration:8, implementation: forward(instructions.res_7_b)!),
            Instruction(opCode: 0xB9, length: 1, name: "RES 7, C", duration:8, implementation: forward(instructions.res_7_c)!),
            Instruction(opCode: 0xBA, length: 1, name: "RES 7, D", duration:8, implementation: forward(instructions.res_7_d)!),
            Instruction(opCode: 0xBB, length: 1, name: "RES 7, E", duration:8, implementation: forward(instructions.res_7_e)!),
            Instruction(opCode: 0xBC, length: 1, name: "RES 7, H", duration:8, implementation: forward(instructions.res_7_h)!),
            Instruction(opCode: 0xBD, length: 1, name: "RES 7, L", duration:8, implementation: forward(instructions.res_7_l)!),
            Instruction(opCode: 0xBE, length: 1, name: "RES 7, (HL)", duration:16, implementation: forward(instructions.res_7_hlp)!),
            Instruction(opCode: 0xBF, length: 1, name: "RES 7, A", duration:8, implementation: forward(instructions.res_7_a)!),
            Instruction(opCode: 0xC0, length: 1, name: "SET 0, B", duration:8, implementation: forward(instructions.set_0_b)!),
            Instruction(opCode: 0xC1, length: 1, name: "SET 0, C", duration:8, implementation: forward(instructions.set_0_c)!),
            Instruction(opCode: 0xC2, length: 1, name: "SET 0, D", duration:8, implementation: forward(instructions.set_0_d)!),
            Instruction(opCode: 0xC3, length: 1, name: "SET 0, E", duration:8, implementation: forward(instructions.set_0_e)!),
            Instruction(opCode: 0xC4, length: 1, name: "SET 0, H", duration:8, implementation: forward(instructions.set_0_h)!),
            Instruction(opCode: 0xC5, length: 1, name: "SET 0, L", duration:8, implementation: forward(instructions.set_0_l)!),
            Instruction(opCode: 0xC6, length: 1, name: "SET 0, (HL)", duration:16, implementation: forward(instructions.set_0_hlp)!),
            Instruction(opCode: 0xC7, length: 1, name: "SET 0, A", duration:8, implementation: forward(instructions.set_0_a)!),
            Instruction(opCode: 0xC8, length: 1, name: "SET 1, B", duration:8, implementation: forward(instructions.set_1_b)!),
            Instruction(opCode: 0xC9, length: 1, name: "SET 1, C", duration:8, implementation: forward(instructions.set_1_c)!),
            Instruction(opCode: 0xCA, length: 1, name: "SET 1, D", duration:8, implementation: forward(instructions.set_1_d)!),
            Instruction(opCode: 0xCB, length: 1, name: "SET 1, E", duration:8, implementation: forward(instructions.set_1_e)!),
            Instruction(opCode: 0xCC, length: 1, name: "SET 1, H", duration:8, implementation: forward(instructions.set_1_h)!),
            Instruction(opCode: 0xCD, length: 1, name: "SET 1, L", duration:8, implementation: forward(instructions.set_1_l)!),
            Instruction(opCode: 0xCE, length: 1, name: "SET 1, (HL)", duration:16, implementation: forward(instructions.set_1_hlp)!),
            Instruction(opCode: 0xCF, length: 1, name: "SET 1, A", duration:8, implementation: forward(instructions.set_1_a)!),
            Instruction(opCode: 0xD0, length: 1, name: "SET 2, B", duration:8, implementation: forward(instructions.set_2_b)!),
            Instruction(opCode: 0xD1, length: 1, name: "SET 2, C", duration:8, implementation: forward(instructions.set_2_c)!),
            Instruction(opCode: 0xD2, length: 1, name: "SET 2, D", duration:8, implementation: forward(instructions.set_2_d)!),
            Instruction(opCode: 0xD3, length: 1, name: "SET 2, E", duration:8, implementation: forward(instructions.set_2_e)!),
            Instruction(opCode: 0xD4, length: 1, name: "SET 2, H", duration:8, implementation: forward(instructions.set_2_h)!),
            Instruction(opCode: 0xD5, length: 1, name: "SET 2, L", duration:8, implementation: forward(instructions.set_2_l)!),
            Instruction(opCode: 0xD6, length: 1, name: "SET 2, (HL)", duration:16, implementation: forward(instructions.set_2_hlp)!),
            Instruction(opCode: 0xD7, length: 1, name: "SET 2, A", duration:8, implementation: forward(instructions.set_2_a)!),
            Instruction(opCode: 0xD8, length: 1, name: "SET 3, B", duration:8, implementation: forward(instructions.set_3_b)!),
            Instruction(opCode: 0xD9, length: 1, name: "SET 3, C", duration:8, implementation: forward(instructions.set_3_c)!),
            Instruction(opCode: 0xDA, length: 1, name: "SET 3, D", duration:8, implementation: forward(instructions.set_3_d)!),
            Instruction(opCode: 0xDB, length: 1, name: "SET 3, E", duration:8, implementation: forward(instructions.set_3_e)!),
            Instruction(opCode: 0xDC, length: 1, name: "SET 3, H", duration:8, implementation: forward(instructions.set_3_h)!),
            Instruction(opCode: 0xDD, length: 1, name: "SET 3, L", duration:8, implementation: forward(instructions.set_3_l)!),
            Instruction(opCode: 0xDE, length: 1, name: "SET 3, (HL)", duration:16, implementation: forward(instructions.set_3_hlp)!),
            Instruction(opCode: 0xDF, length: 1, name: "SET 3, A", duration:8, implementation: forward(instructions.set_3_a)!),
            Instruction(opCode: 0xE0, length: 1, name: "SET 4, B", duration:8, implementation: forward(instructions.set_4_b)!),
            Instruction(opCode: 0xE1, length: 1, name: "SET 4, C", duration:8, implementation: forward(instructions.set_4_c)!),
            Instruction(opCode: 0xE2, length: 1, name: "SET 4, D", duration:8, implementation: forward(instructions.set_4_d)!),
            Instruction(opCode: 0xE3, length: 1, name: "SET 4, E", duration:8, implementation: forward(instructions.set_4_e)!),
            Instruction(opCode: 0xE4, length: 1, name: "SET 4, H", duration:8, implementation: forward(instructions.set_4_h)!),
            Instruction(opCode: 0xE5, length: 1, name: "SET 4, L", duration:8, implementation: forward(instructions.set_4_l)!),
            Instruction(opCode: 0xE6, length: 1, name: "SET 4, (HL)", duration:16, implementation: forward(instructions.set_4_hlp)!),
            Instruction(opCode: 0xE7, length: 1, name: "SET 4, A", duration:8, implementation: forward(instructions.set_4_a)!),
            Instruction(opCode: 0xE8, length: 1, name: "SET 5, B", duration:8, implementation: forward(instructions.set_5_b)!),
            Instruction(opCode: 0xE9, length: 1, name: "SET 5, C", duration:8, implementation: forward(instructions.set_5_c)!),
            Instruction(opCode: 0xEA, length: 1, name: "SET 5, D", duration:8, implementation: forward(instructions.set_5_d)!),
            Instruction(opCode: 0xEB, length: 1, name: "SET 5, E", duration:8, implementation: forward(instructions.set_5_e)!),
            Instruction(opCode: 0xEC, length: 1, name: "SET 5, H", duration:8, implementation: forward(instructions.set_5_h)!),
            Instruction(opCode: 0xED, length: 1, name: "SET 5, L", duration:8, implementation: forward(instructions.set_5_l)!),
            Instruction(opCode: 0xEE, length: 1, name: "SET 5, (HL)", duration:16, implementation: forward(instructions.set_5_hlp)!),
            Instruction(opCode: 0xEF, length: 1, name: "SET 5, A", duration:8, implementation: forward(instructions.set_5_a)!),
            Instruction(opCode: 0xF0, length: 1, name: "SET 6, B", duration:8, implementation: forward(instructions.set_6_b)!),
            Instruction(opCode: 0xF1, length: 1, name: "SET 6, C", duration:8, implementation: forward(instructions.set_6_c)!),
            Instruction(opCode: 0xF2, length: 1, name: "SET 6, D", duration:8, implementation: forward(instructions.set_6_d)!),
            Instruction(opCode: 0xF3, length: 1, name: "SET 6, E", duration:8, implementation: forward(instructions.set_6_e)!),
            Instruction(opCode: 0xF4, length: 1, name: "SET 6, H", duration:8, implementation: forward(instructions.set_6_h)!),
            Instruction(opCode: 0xF5, length: 1, name: "SET 6, L", duration:8, implementation: forward(instructions.set_6_l)!),
            Instruction(opCode: 0xF6, length: 1, name: "SET 6, (HL)", duration:16, implementation: forward(instructions.set_6_hlp)!),
            Instruction(opCode: 0xF7, length: 1, name: "SET 6, A", duration:8, implementation: forward(instructions.set_6_a)!),
            Instruction(opCode: 0xF8, length: 1, name: "SET 7, B", duration:8, implementation: forward(instructions.set_7_b)!),
            Instruction(opCode: 0xF9, length: 1, name: "SET 7, C", duration:8, implementation: forward(instructions.set_7_c)!),
            Instruction(opCode: 0xFA, length: 1, name: "SET 7, D", duration:8, implementation: forward(instructions.set_7_d)!),
            Instruction(opCode: 0xFB, length: 1, name: "SET 7, E", duration:8, implementation: forward(instructions.set_7_e)!),
            Instruction(opCode: 0xFC, length: 1, name: "SET 7, H", duration:8, implementation: forward(instructions.set_7_h)!),
            Instruction(opCode: 0xFD, length: 1, name: "SET 7, L", duration:8, implementation: forward(instructions.set_7_l)!),
            Instruction(opCode: 0xFE, length: 1, name: "SET 7, (HL)", duration:16, implementation: forward(instructions.set_7_hlp)!),
            Instruction(opCode: 0xFF, length: 1, name: "SET 7, A", duration:8, implementation: forward(instructions.set_7_a)!)
        ]
    }
}
