// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GameBoyEmulator",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "GameBoyEmulator",
            targets: ["AppModule"],
            bundleIdentifier: "marcalx.TT",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .gamepad),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readWrite),
                .fileAccess(.downloadsFolder, mode: .readWrite)
            ],
            appCategory: .games
        )
    ],
    dependencies: [
        .package(path: "../../packages/GBUIKit"),
        .package(path: "../../packages/GBKit")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "GBUIKit", package: "GBUIKit"),
                .product(name: "GBKit", package: "GBKit")
            ],
            path: "."
        )
    ]
)
